# Generated by Django 6.0.4 on 2026-04-19 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerErrorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_category', models.CharField(max_length=20)),
                ('total_errors', models.PositiveIntegerField(default=0)),
                ('first_attempt_successes', models.PositiveIntegerField(default=0)),
                ('avg_hints_used', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_summaries', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_summaries', to='submissions.textsubmission')),
            ],
            options={
                'ordering': ['-submission__submitted_at', 'error_category'],
                'unique_together': {('student', 'submission', 'error_category')},
            },
        ),
    ]
