# Generated by Django 6.0.4 on 2026-04-19 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_category', models.CharField(choices=[('grammar', 'Grammar'), ('spelling', 'Spelling'), ('article', 'Article'), ('preposition', 'Preposition'), ('verb_tense', 'Verb Tense'), ('punctuation', 'Punctuation'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('original_text', models.TextField()),
                ('hint_text', models.TextField(blank=True)),
                ('correct_solution', models.TextField()),
                ('languagetool_rule_id', models.CharField(blank=True, max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='submissions.textsubmission')),
            ],
            options={
                'ordering': ['start_offset'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('attempted_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('hint_shown', models.BooleanField(default=False)),
                ('solution_shown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_attempts', to=settings.AUTH_USER_MODEL)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='feedback.detectederror')),
            ],
            options={
                'ordering': ['error', 'attempt_number'],
                'unique_together': {('error', 'attempt_number')},
            },
        ),
    ]
